name: Build RPM package
on:
  workflow_dispatch: {}

jobs:
  rpm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build RPM
        run: docker run -t --rm -v "${PWD}":/home/builder/rpmbuild/SOURCES docker.io/mhutter/rpmbuild rpmbuild -bb rpmbuild/SPECS/ansible-dynamic-inventory-ec2.spec
      - name: Store RPM as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: rpm
          path: redhat/rpms/
